# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GTToast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GTToast

  target 'GTToastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GTToastUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  #在此版本上兼容
  pod 'MBProgressHUD', '1.1.0'

end
